Import des bibliothèques

In [ ]:
import pandas as pd
import numpy as np
import duckdb

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
pd.set_option('display.max_colwidth',None) #permet d'avoir le contenu complet des colonnes dans le dataframe

Chargement du dataset

In [ ]:
df2019 = pd.read_csv('/customers.csv')
df2019.head(12)

,date,customer_id,article_id,price,type_commerce,quantity,revenue
0,2019-01-01,0005f3aab821000881d74b72fde2d9b3e4742cf86136681c6c7d107cd9452d59,304766008,0.022017,2,3,0.066051
1,2019-01-01,000ca60ca6d8de6d3b4689e2da829d69db5947bd89084cd3a0849f4ea57375fd,662916002,0.022017,2,1,0.022017
2,2019-01-01,000ca60ca6d8de6d3b4689e2da829d69db5947bd89084cd3a0849f4ea57375fd,740909001,0.042356,2,1,0.042356
3,2019-01-01,001ea5b25c75e6490705b22abb670e08007967c631a4c5a9c1473857d2fa41e2,666382002,0.015237,2,1,0.015237
4,2019-01-01,0020214808da2ebeee7b8eb0fe5bc50bb4f7f52c37ccfff693a080b5d1017134,583534009,0.016932,2,1,0.016932
5,2019-01-01,0020214808da2ebeee7b8eb0fe5bc50bb4f7f52c37ccfff693a080b5d1017134,583534018,0.016932,2,1,0.016932
6,2019-01-01,00497856651e5483f26917703886e95c6e299a7492874087ec4a2d78acc4f081,399256001,0.016932,2,1,0.016932
7,2019-01-01,00497856651e5483f26917703886e95c6e299a7492874087ec4a2d78acc4f081,519583033,0.033881,2,1,0.033881
8,2019-01-01,00497856651e5483f26917703886e95c6e299a7492874087ec4a2d78acc4f081,665532003,0.101678,2,1,0.101678
9,2019-01-01,0054357b9f186ddab5b7aa49d912929fb9895d282232625eda6dd53632a54cfd,626887003,0.013542,2,1,0.013542
10,2019-01-01,0054357b9f186ddab5b7aa49d912929fb9895d282232625eda6dd53632a54cfd,651346002,0.008119,2,1,0.008119
11,2019-01-01,0054357b9f186ddab5b7aa49d912929fb9895d282232625eda6dd53632a54cfd,699667001,0.033898,2,1,0.033898

Chargement du 2e dataset

In [ ]:
cust = pd.read_csv('/Copie de customers_clean.csv')
cust.head(10)

,customer_id,FN,club_member_status,fashion_news_frequency,age,postal_code
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3d25f88aa139fdfc657,0.0,ACTIVE,NONE,49,52043ee2162cf5aa7ee79974281641c6f11a68d276429a91f8ca0d4b6efa8100
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051eec9c12fb36984420fa,0.0,ACTIVE,NONE,25,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93f4c830291c32bc3057
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0cad8ffe7ad4a1091e318,0.0,ACTIVE,NONE,24,64f17e6a330a85798e4998f62d0930d14db8db1c054af6c9090f7dd3e38380dc
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2c5feb1ca5dff07c43e,0.0,ACTIVE,NONE,54,5d36574f52495e81f019b680c843c443bd343d5ca5b1c222539af5973a23ae6d
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801fe7fc0f26dd8d65a85a,1.0,ACTIVE,Regularly,52,25fa5ddee9aac01b35208d01736e57942317d756b32ddd4564743b005a805b1d
5,000064249685c11552da43ef22a5030f35a147f723d5b02ddd9fd22452b1f5a6,0.0,unknown,unknown,32,2c29ae653a9282cce4151bd87643c907644e09541abc28ae87dea0d1f6603b1c
6,0000757967448a6cb83efb3ea7a3fb9d418ac7adf2379d8cd0c725276a467a2a,0.0,ACTIVE,NONE,20,fe7b8e2b3fafb89ca90db17ffeeae0fd29b795d803f74961cf8f27adb16e67e4
7,00007d2de826758b65a93dd24ce629ed66842531df6699338c5570910a014cc2,1.0,ACTIVE,Regularly,32,8d6f45050876d059c830a0fe63f1a4c022de279bb68ce312615afb86814fec7a
8,00007e8d4e54114b5b2a9b51586325a8d0fa74ea23ef77334eaec4ffccd7ebcc,0.0,ACTIVE,NONE,20,2c29ae653a9282cce4151bd87643c907644e09541abc28ae87dea0d1f6603b1c
9,00008469a21b50b3d147c97135e25b4201a8c58997f78782a0cc706645e14493,0.0,ACTIVE,NONE,20,2c29ae653a9282cce4151bd87643c907644e09541abc28ae87dea0d1f6603b1c

Exploration initiale des données

In [ ]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1371980 entries, 0 to 1371979
Data columns (total 6 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   customer_id             1371980 non-null  object
 1   FN                      1371980 non-null  float64
 2   club_member_status      1371980 non-null  object
 3   fashion_news_frequency  1371980 non-null  object
 4   age                     1371980 non-null  int64
 5   postal_code             1371980 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 62.8+ MB

In [ ]:
# Connexion en mémoire (ou fichier .db si tu veux sauvegarder)
con = duckdb.connect(database=':memory:')

Jointure des 2 DataFrames

In [ ]:
csv_files = [

    '/Copie de df_2019_clean.csv',
    '/Copie de cust_clean.csv',
]

# Supprimer toutes les tables existantes avant de recréer
tables = con.execute("SHOW TABLES").fetchall()
for t in tables:
    con.execute(f"DROP TABLE IF EXISTS {t[0]}")

# Charger les CSV
for i, file in enumerate(csv_files, start=1):
    table_name = f'table{i}'

    # Forcer la colonne "date" en VARCHAR pour éviter l'erreur
    con.execute(f"""
        CREATE TABLE {table_name} AS
        SELECT * FROM read_csv_auto('{file}', types={{'date': 'VARCHAR'}}, ignore_errors=True)
    """)
    print(f"{table_name} chargé")

Anonymisation des données clients avec Faker

In [ ]:
from faker import Faker

fake = Faker("fr_FR")

# mapping customer_id -> nom fictif
customer_name_map = {
    cid: fake.name()
    for cid in custo2019["customer_id"].unique()
}

# mapping postal_code -> postal fictif
postal_code_map = {
    pc: fake.postcode()
    for pc in custo2019["postal_code"].unique()
}

# application
custo2019["name_fake"] = custo2019["customer_id"].map(customer_name_map)
custo2019["postal_code_fake"] = custo2019["postal_code"].map(postal_code_map)

In [ ]:
custo2019clean = custo2019.drop(columns=["postal_code"])

In [ ]:
# Convertir la colonne 'date' en datetime
custo2019clean['date'] = pd.to_datetime(custo2019['date'], errors='coerce')

Mise à l’échelle des prix et des revenus et vérification des statistiques.

In [ ]:
# Choix d'un facteur pour ramener les prix à l'échelle réaliste
facteur = 1000

# Transformation des colonnes
custo2019clean['price_real'] = custo2019['price'] * facteur
custo2019clean['revenue_real'] = custo2019['revenue'] * facteur

# Vérification des statistiques
custo2019clean[['price_real', 'revenue_real']].describe()

       price_real  revenue_real
count  5994661.00    5994661.00
mean        27.94         31.16
std         18.26         24.79
min          0.17          0.17
25%         16.93         16.93
50%         25.41         25.41
75%         33.88         36.00
max        506.78       5083.90

In [ ]:
!pip install gender-guesser

Collecting gender-guesser
  Downloading gender_guesser-0.4.0-py2.py3-none-any.whl.metadata (3.0 kB)
Downloading gender_guesser-0.4.0-py2.py3-none-any.whl (379 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 379.3/379.3 kB 10.2 MB/s eta 0:00:00
Installing collected packages: gender-guesser
Successfully installed gender-guesser-0.4.0

Estimation du genre des clients à partir de leur prénom.

In [ ]:
import gender_guesser.detector as gender

d = gender.Detector()
custo2019clean['prenom'] = custo2019clean['name_fake'].str.split().str[0]

# Détecter le genre
custo2019clean['genre'] = custo2019clean['prenom'].apply(lambda x: d.get_gender(x))

# Simplifier
def simplifier(val):
    if val in ['male', 'mostly_male']:
        return 'H'
    elif val in ['female', 'mostly_female']:
        return 'F'
    else:
        return 'U'

custo2019clean['genre'] = custo2019clean['genre'].apply(simplifier)

Création du dataset clients avec les variables nécessaires à l’analyse.

In [ ]:
df_customers=custo2019clean["customer_id","FN","club_member_status","fashion_news_frequency","age","postal_code_fake","date"]

Telechargement du csv

In [ ]:
df_customers.to_csv("csv/customers_clean.csv", index=False)